export const CREATE_CARD = 'CREATE_CARD';
export const INCREASE_PAGES = 'INCREASE_PAGES';
export const UPDATE_CURRENT_CARDS = 'UPDATE_CURRENT_CARDS';
export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE';
